### ISSUE TITLE
Results don't seem as good as the paper from a user.

### ISSUE THREAD

**Issue by Dibbidy** [frank-xwang/InstanceDiffusion#1]
>I wasn't up for editing their demo to load safetensors to pick out a better finetune, so this is with the SD1.5 ckpt. I ran a couple other sets of these, and none seem to be as well composited together compared to the papers results. These all do have the refiner used on them, but the originals still have the same artifacts.

![ns6331gg1xgc1](https://github.com/frank-xwang/InstanceDiffusion/assets/153976572/ee2976d6-2346-4e10-b65e-e55d6271d711)

**Comment by frank-xwang** [comment]
Hello, and thank you for showing interest in our work.

For instance generation involving parts or subparts, they are expected to be contained within the bounds of the instance box. Could you please ensure the part/subpart boxes are positioned within the instance box before generating again? It's been observed that placing subpart or part boxes in uncommon locations might compromise the quality of instance generation.

As for generating human images, the base model utilized in this repository, Stable Diffusion, faces challenges in this area. We believe that adopting a more sophisticated base model, one that's optimized/tuned for human generation, could significantly enhance outcomes.

Thank you!
