### ISSUE TITLE
training dataloader issue

### ISSUE THREAD

**Issue by 2a3b4c** [frank-xwang/InstanceDiffusion#10]
![1709129880833](https://github.com/frank-xwang/InstanceDiffusion/assets/40889570/657d0cc0-0dbc-49ff-854f-3e1eaee0b2e0)
how to get the "projection_matrix" file?

**Comment by frank-xwang** [comment]
Hi, projection_matrix (768*768) is the CLIP projection matrix, which should be weight.data of Linear layer defined in CLIP (out_dim, in_dim). We actually didn't use the image embedding, therefore, you can comment out this line. Let me know if you have further questions.

**Comment by frank-xwang** [comment]
update: I have pushed the codes with this line cemented out, plz let me know if you meet other issues.

**Comment by 2a3b4c** [comment]
I review the decode processed data, and find the corresponding caption of every segmantion is empty, is it normal?

**Comment by 2a3b4c** [comment]
thanks for your answer, i used the coco dataset to process, and the key "is_det" in data is 0, so caption information in the decoded data can not be obtained. 
I just wander waht the key "is_det" meaning? and the meaning of o365 in the corresponding comment "# if it is from detection (such as o365), then we will make a pseudo caption"

**Comment by frank-xwang** [comment]
If `is_det` is 0, the model will use the generated instance captions. Otherwise, it will use the category name (from ground-truth or an object detection model) as the pseudo instance caption.
