### ISSUE TITLE
ldm.module has no attribute PositionNet

### ISSUE THREAD

**Issue by whosthemaan** [frank-xwang/InstanceDiffusion#12]
Hi, I am getting the following error after I have all the required libraries set up using the given requirements.txt with conda environment.

![image](https://github.com/frank-xwang/InstanceDiffusion/assets/40595475/ee53ee29-3728-4390-a84d-dccf3fc5dd1c)

Thanks

**Comment by frank-xwang** [comment]
Hi, did you follow our [instructions on mode inference](https://github.com/frank-xwang/InstanceDiffusion#instancediffusion-inference-demons)? You can run the model inference following this code:

python inference.py \
  --num_images 8 \
  --output OUTPUT/ \
  --input_json demos/demo_cat_dog_robin.json \
  --ckpt pretrained/instancediffusion_sd15.pth \
  --test_config configs/test_box.yaml \
  --guidance_scale 5 \
  --alpha 0.8 \
  --seed 0 \
  --mis 0.36 \
  --cascade_strength 0.3 \

I just tried it locally, it worked fine. Let me know if it does not work for you.
