### ISSUE TITLE
How to run the train code, I get the follwing error? Do I need to configure an additional environment to run

### ISSUE THREAD

**Issue by heart-du** [frank-xwang/InstanceDiffusion#13]
Traceback (most recent call last):
  File "/home/ma-user/work/d00563493/code/InstanceDiffusion/run_with_submitit.py", line 123, in <module>
    main()
  File "/home/ma-user/work/d00563493/code/InstanceDiffusion/run_with_submitit.py", line 83, in main
    args.job_dir = get_shared_folder() / "%j"
  File "/home/ma-user/work/d00563493/code/InstanceDiffusion/run_with_submitit.py", line 34, in get_shared_folder
    raise RuntimeError("No shared folder available")

**Comment by frank-xwang** [comment]
Hi, the shared folder should be the folder that is visible by all machines / nodes. You can change the path "/fsx-muvigen/" in [line 30](https://github.com/frank-xwang/InstanceDiffusion/blob/d0836d86d6da9aa3a0c4a3cfe08d12965e751a8e/run_with_submitit.py#L30) to the shared folder in your env. You can also simple use your home directory if it is visible by all nodes.

**Comment by heart-du** [comment]
thanks for reply, I also want know how to get projection_matrix.

**Comment by frank-xwang** [comment]
Hi, projection_matrix (768*768) is the CLIP projection matrix, which should be weight.data of Linear layer defined in CLIP (out_dim, in_dim). We actually didn't use it in our codes.

**Comment by frank-xwang** [comment]
Closing this issue now. Please feel free to re-open it if you have further questions.
