### ISSUE TITLE
Can you privide a simple demo json for training your model

### ISSUE THREAD

**Issue by zhengziqiang** [frank-xwang/InstanceDiffusion#14]
Could you please provide a simple json file for training to let us know what kind of data structure is needed?

The json file could contain some meaningless placeholders. Just let us know the input structure is ok. Thank you for your help in advance

**Comment by zhengziqiang** [comment]
Because I am following your instructions.

I found no "Tag2Text" directory in GroundedSAM

line 29 in "dataset-generation/submitit_automatic_label_ram_save_json.py",

It is really confusing.

**Comment by zhengziqiang** [comment]
Really cannot run the data generation following your instructions. Could you please help with this? Or just provide some demo jsons?

**Comment by zhengziqiang** [comment]
Thank you for your help. The code can run successfully but I met the out-of-memory issue. I plan to do this step-by-step.

**Comment by 66ling66** [comment]
Hello do you get the training data successfully?

**Comment by sweetDream6609** [comment]
Hello do you get the training data successfully?Could you please provide a simple json file for training to let us know what kind of data structure is needed?I am plan to generat data by myself.
