### ISSUE TITLE
Training using main_submitit.py

### ISSUE THREAD

**Issue by Shinjiteru** [frank-xwang/InstanceDiffusion#28]
I have tried running the main_submitit.py for training but faced with this error
![image](https://github.com/frank-xwang/InstanceDiffusion/assets/54525366/4e549605-b606-4643-a5a4-0767af77f423)

I traced the code base and reached this section where it is required to load 'projection_matrix', any idea how to resolve this issue?
![image](https://github.com/frank-xwang/InstanceDiffusion/assets/54525366/24d8b960-bb0d-4073-b2f5-64ce24159980)

**Comment by frank-xwang** [comment]
Hi, I have updated the codebase to fix this issue. Please let me know if the issue is still unsolved.

**Comment by Shinjiteru** [comment]
Resolved thanks!
