### ISSUE TITLE
Questions about "train_data.txt".

### ISSUE THREAD

**Issue by l412198735** [frank-xwang/InstanceDiffusion#29]
Thank you for your valuable work! Could you provide an example of an image caption for 'train_data.txt'? Is it a sentence like:
 { "image": "/xxx.jpg", 
"caption": "a yellow American robin, a brown Maltipoo dog, a gray British Shorthair in a stream, alongside trees and rocks" }," 
} ?

**Comment by sweetDream6609** [comment]
hello，I want to know if "train_data.txt" is as you said？
