### ISSUE TITLE
InstanceDiffusion for SDXL

### ISSUE THREAD

**Issue by Cominclip** [frank-xwang/InstanceDiffusion#3]
This is an outstanding work! Do you have any plans to train InstanceDiffusion on SDXL?

**Comment by frank-xwang** [comment]
Hi, thank you for your interest! :-) At the moment, we follow the previous work GLIGEN or DenseDiffusion and use SD1.X as the base model. Our support is limited to the SDXL-Refiner, but expanding InstanceDiffusion to train on SDXL is a direction we intend to explore in the future.

**Comment by Cominclip** [comment]
Thank you for your response. I look forward to your future work.

**Comment by eezywu** [comment]
> Hi, thank you for your interest! :-) At the moment, we follow the previous work GLIGEN or DenseDiffusion and use SD1.X as the base model. Our support is limited to the SDXL-Refiner, but expanding InstanceDiffusion to train on SDXL is a direction we intend to explore in the future.

nice work! looking forward to the SDXL version :)
