### ISSUE TITLE
diffusers support?

### ISSUE THREAD

**Issue by zzhang2816** [frank-xwang/InstanceDiffusion#4]
Thanks for your impressive work! Is there any plan to support diffusers?

**Comment by frank-xwang** [comment]
Thank you for your interest in InstanceDiffusion! As this repository is a re-implementation, our current focus is on supporting model training, evaluation, and benchmarking first. Supporting diffusers is planned but has a lower priority at the moment. Please stay tuned for updates. Thanks!

**Comment by zzhang2816** [comment]
Thanks for your reply!
