### ISSUE TITLE
generated training dict missing some keys.

### ISSUE THREAD

**Issue by zxduan90** [frank-xwang/InstanceDiffusion#5]
The jsondataset decode func needs "image_embedding_before", "text_embedding_before", "image_embedding_after", "text_embedding_after", but only "text_embedding_before" is generated.

**Comment by frank-xwang** [comment]
Hi thank you for noticing it! I've updated the codebase and addressed the bug. Please don't hesitate to reopen the issue if you encounter any further problems. :-)
