### ISSUE TITLE
question about Instance-Masked Attention

### ISSUE THREAD

**Issue by jsg921019** [frank-xwang/InstanceDiffusion#6]
Thank you for  sharing interesting work.

I have question about Instance-Masked Attention.
Current code does not seems to apply Instance-Masked Attention. (return_att_masks =  False)
Is this because not applying Instance-Masked Attention is better in generation quality?

Secondly, is Instance-Masked Attention applied when training? Or is this only applied when inference?

Thank you in advance.

**Comment by frank-xwang** [comment]
Hi, thank you for expressing your interest. Currently, we have `return_att_masks` set to `False` as Flash Attention does not yet support attention masks (check [it](https://github.com/Dao-AILab/flash-attention/issues/352) here). However, if speed and memory usage are not primary concerns for your application, you may opt to set `return_att_masks` to `True`. It's worth noting that during our learning process, we had this option enabled. Hope it helps!

**Comment by jsg921019** [comment]
Thank you for precise and fast feedback!
