### ISSUE TITLE
inference.py have bug

### ISSUE THREAD

**Issue by machine52vision** [frank-xwang/InstanceDiffusion#8]
File "E:\MWDeepLearning\1.Train\16.Gen_Defect\InstanceDiffusion-main\ldm\util.py", line 86, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
AttributeError: module 'ldm.modules.diffusionmodules.text_grounding_net' has no attribute 'PositionNet'

**Comment by frank-xwang** [comment]
Hi, did you follow our [instructions on mode inference](https://github.com/frank-xwang/InstanceDiffusion#instancediffusion-inference-demons)? You can run the model inference following this code:

```
python inference.py \
  --num_images 8 \
  --output OUTPUT/ \
  --input_json demos/demo_cat_dog_robin.json \
  --ckpt pretrained/instancediffusion_sd15.pth \
  --test_config configs/test_box.yaml \
  --guidance_scale 5 \
  --alpha 0.8 \
  --seed 0 \
  --mis 0.36 \
  --cascade_strength 0.3 \
```

I just tried it locally, it worked fine. Let me know if it does not work for you.

**Comment by machine52vision** [comment]
> configs

thanks,it work!
