### ISSUE TITLE
whether the training data can be released

### ISSUE THREAD

**Issue by 2a3b4c** [frank-xwang/InstanceDiffusion#9]
Good work! I just wander whether the training dataset can be released? thanks!

**Comment by frank-xwang** [comment]
Thank you for your interest in our research! Regrettably, we are not permitted to release it. :-( However, you can visit our [dataset-generation section](https://github.com/frank-xwang/InstanceDiffusion/tree/main/dataset-generation) to discover how to generate training data using your own dataset. Thank you!
